#!/usr/bin/env python

# Copyright (C) 2014 Science and Technology Facilities Council.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

from os.path import basename
import sys

from pymoc.util.tool import MOCTool, CommandError


def main():
    """Main routine to run the pymoc tool."""

    name = basename(sys.argv[0])
    tool = MOCTool()

    try:
        tool.run(sys.argv[1:])

    except CommandError as e:
        print(name + ':', e.message, file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()
